name: deploy

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        if: |
            contains(github.event.head_commit.message, 'patch') ||
            contains(github.event.head_commit.message, 'fixes') ||
            contains(github.event.head_commit.message, 'major') ||
            contains(github.event.head_commit.message, 'release') ||
            contains(github.event.head_commit.message, 'minor')
        steps:
            - name: Check out the repo
              uses: actions/checkout@v3
              with:
                  token: ${{ secrets.TOKEN_GITHUB }}

            - name: "Automated Version Bump"
              uses: "phips28/gh-action-bump-version@master"
              id: version
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
                  PACKAGEJSON_DIR: "backend"
              with:
                  minor-wording: "minor"
                  major-wording: "major,release"
                  patch-wording: "patch,fixes"

            - name: Login to Docker Hub
              uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD  }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ${{ secrets.DOCKERHUB_USERNAME }}/shop

            - name: Build and push
              uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/shop:${{steps.version.outputs.newTag}}
                  labels: ${{ secrets.DOCKERHUB_USERNAME }}/shop:${{steps.version.outputs.newTag}}

            - name: Wait for Render Deployment
              uses: bounceapp/render-action@0.6.0
              with:
                  render-token: ${{ secrets.RENDER_TOKEN }}
                  github-token: ${{ secrets.TOKEN_GITHUB }}
                  service-id: ${{ secrets.RENDER_SERVICE_ID }}
                  retries: 20
                  wait: 16000
                  sleep: 30000
